return {
    'neovim/nvim-lspconfig',
    config = function()
        local lspconfig = require('lspconfig')
        lspconfig.bashls.setup({})
        lspconfig.clangd.setup({})
        lspconfig.omnisharp.setup({})
        lspconfig.cssls.setup({})
        lspconfig.dockerls.setup({})
        lspconfig.docker_compose_language_service.setup({})
        lspconfig.eslint.setup({})
        lspconfig.gopls.setup({})
        lspconfig.html.setup({})
        lspconfig.htmx.setup({})
        lspconfig.jsonls.setup({})
        lspconfig.tsserver.setup({})
        lspconfig.lua_ls.setup({})
        lspconfig.marksman.setup({})
        lspconfig.pyright.setup({})
        lspconfig.rust_analyzer.setup({})
        lspconfig.sqlls.setup({})
        lspconfig.svelte.setup({})
        lspconfig.tailwindcss.setup({})
        lspconfig.lemminx.setup({})
        lspconfig.hydra_lsp.setup({})
        lspconfig.zls.setup({})
        vim.keymap.set('n', 'K', vim.lsp.buf.hover, {})
        vim.keymap.set('n', 'gd', vim.lsp.buf.definition, {})
        vim.keymap.set({ 'n', 'v' }, '<leader>ca', vim.lsp.buf.code_action, {})
    end
}
